In [1]:
import pandas as pd

## reading data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infecProb
0   99.848105         0   91          1          -1          0
1   98.930167         0   72          1           0          1
2  101.601133         0   52          0           0          0
3   99.563121         1   17          1           1          1
4  100.142759         0   75          1           0          0

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infecProb
2996  100.160574         1    6          0           1          1
2997  101.757908         1   25          1           0          0
2998  100.202157         1   18          1          -1          0
2999   98.500000         0   30          0          -1          0
3000   98.500000         0   30          0           0          0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3001 entries, 0 to 3000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   fever       3001 non-null   float64
 1   bodyPain    3001 non-null   int64  
 2   age         3001 non-null   int64  
 3   runnyNose   3001 non-null   int64  
 4   diffBreath  3001 non-null   int64  
 5   infecProb   3001 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 140.8 KB


In [6]:
df['diffBreath'].value_counts()

-1    1047
 0     999
 1     955
Name: diffBreath, dtype: int64

In [7]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  3001.000000  3001.000000  3001.000000  3001.000000  3001.000000   
mean     99.996527     0.486504    50.110297     0.498834    -0.030656   
std       1.151509     0.499901    28.695879     0.500082     0.816329   
min      98.001229     0.000000     1.000000     0.000000    -1.000000   
25%      99.016773     0.000000    25.000000     0.000000    -1.000000   
50%      99.974494     0.000000    51.000000     0.000000     0.000000   
75%     100.991560     1.000000    74.000000     1.000000     1.000000   
max     101.999989     1.000000   100.000000     1.000000     1.000000   

         infecProb  
count  3001.000000  
mean      0.515162  
std       0.499853  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

## Train Test Splitting

In [8]:
import numpy as np

In [9]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size=int(len(data)* ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]



In [10]:
np.random.permutation(10)

array([5, 9, 1, 0, 7, 4, 2, 8, 3, 6])

In [11]:
train, test= data_split(df, 0.2)

In [12]:
train

fever  bodyPain  age  runnyNose  diffBreath  infecProb
642   100.470939         1   33          1           1          1
700   100.284722         1   68          1          -1          1
226   101.317254         1   72          1           0          1
1697   99.153220         1   92          0           0          1
1010   98.612455         0   91          1           0          1
...          ...       ...  ...        ...         ...        ...
1638   98.532688         1   92          1           0          1
1095   99.940401         0   66          1          -1          1
1130  101.976233         0   19          0           0          1
1294   99.321473         1   37          0          -1          1
860    98.610961         1   49          1           0          0

[2401 rows x 6 columns]

In [13]:
test

fever  bodyPain  age  runnyNose  diffBreath  infecProb
1801  101.572827         1    3          0           0          1
1190  100.006884         0   82          1           1          1
1817  101.400468         1   52          1           0          1
251    99.042276         0   46          1          -1          1
2505   99.522210         0   22          0           0          1
...          ...       ...  ...        ...         ...        ...
104   100.282857         1   16          1           0          1
2087  100.147270         1   38          1           0          0
599    99.823726         1   47          1          -1          0
1756   99.009317         1   25          1           1          0
1323  100.064174         0   52          0           1          0

[600 rows x 6 columns]

In [14]:
x_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
x_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [15]:
x_train

array([[100.4709392 ,   1.        ,  33.        ,   1.        ,
          1.        ],
       [100.284722  ,   1.        ,  68.        ,   1.        ,
         -1.        ],
       [101.3172541 ,   1.        ,  72.        ,   1.        ,
          0.        ],
       ...,
       [101.9762331 ,   0.        ,  19.        ,   0.        ,
          0.        ],
       [ 99.32147257,   1.        ,  37.        ,   0.        ,
         -1.        ],
       [ 98.61096096,   1.        ,  49.        ,   1.        ,
          0.        ]])

In [16]:
x_test

array([[101.5728268 ,   1.        ,   3.        ,   0.        ,
          0.        ],
       [100.0068838 ,   0.        ,  82.        ,   1.        ,
          1.        ],
       [101.4004679 ,   1.        ,  52.        ,   1.        ,
          0.        ],
       ...,
       [ 99.82372587,   1.        ,  47.        ,   1.        ,
         -1.        ],
       [ 99.00931659,   1.        ,  25.        ,   1.        ,
          1.        ],
       [100.0641744 ,   0.        ,  52.        ,   0.        ,
          1.        ]])

In [17]:
y_train = train[['infecProb']].to_numpy().reshape(2401 ,)
y_test = test[['infecProb']].to_numpy().reshape(600 ,)

In [18]:
y_train

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
clf = LogisticRegression()
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
inputFeatures=[103.3,1,50,1,1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [22]:
infProb

0.5200430964281335